[workspace]
resolver = "2"
members = [
    "client",
    "server",
    "shared",
    "store",
    "repl",
]


[profile.release.package.client]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
